---
- name: Установка Docker
  block:
    - name: --=Add repository universe=--
      apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"

    - name: Install depends
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: true
        cache_valid_time: 86400

    - name: --=Add docker repo key=--
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: --=Add docker repository=--
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update-cache: true
        filename: "docker"

    - name: --=Install docker=--
      apt:
        name: docker-ce
        update_cache: true
        state: present

    - name: --=Check docker service=--
      service:
        name: docker
        state: restarted
        enabled: yes

- name: Установка Docker-compose
  block:
    - name: --=Get version docker-compose latest =--
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: compose

    - name: -=Download docker-compose=--
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose.json.tag_name }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755

- name: Завершение инициализации
  block:
    - name: --=Add user to docker group=--
      user:
        name: "{{ansible_user}}"
        groups: docker
        append: yes

    - debug:
        msg: "That's all"

