- name: "***{{ name }}*** Deploy service"
  community.docker.docker_swarm_service:
    name: "{{ name }}"
    image: nginx:latest
    state: present
    networks:
      - name: {{ network_name }}
    publish:
      - mode: ingress
        protocol: tcp
        published_port: 80
        target_port: 8080
